### ISSUE TITLE
Impossible to operate wLightBox v1, v2 in mode CCT x2

### ISSUE THREAD

**Issue by riokuu** [blebox/blebox_uniapi#138]
* BleBox Python UniAPI version: 2.1.0, 2.1.1
* Python version: ANY
* Operating System: N/A

### Description

Impossible to operate wLightBox v1, v2 in mode CCT x2
### What I Did
Issue noticed in:
https://github.com/home-assistant/core/issues/80124

Currently request sending values on channels sends information for 5 channels.

While device's extended state provides colorMode info, following masks are used to operate on proper channels.

`ctx2 = {"cct1": lambda x: f"{x}------", "cct2": lambda x: f"----{x}--"}`

Devices v1, v2, operate on 4 channels only.

TODO:
Check the extended state's desiredColor length on Light class init to later truncate desiredColor value.

**Comment by SebastianRajca** [comment]
I have the same problem with only one instaled CCT channel.

**Comment by riokuu** [comment]
Issue resolved in https://github.com/blebox/blebox_uniapi/releases/tag/v2.1.2
