### ISSUE TITLE
Błędnie działająca integracja dla thermobox

### ISSUE THREAD

**Issue by shibby20** [blebox/blebox_uniapi#142]
Integracja działała poprawnie do HA wersji z grudnia 2022 (testowałem na 2022.12.4). Na wersjach tegorocznych (2023.1.7 oraz 2023.2.1) integracja nie aktualizuje poprawnie stanu encji gdy thermobox jest wyłączony - stan encji pozostaje "heat", zmienia się jedynie atrybut hvac_action na off. Czy problem jest Wam znany? Jeżeli mam rozwinąć problem, zamieścić screeny to proszę informację.
Pozdrawiam

**Comment by riokuu** [comment]
Witam, zweryfikowałem problem na obrazie dokerowym w z tagiem latest na tę chwilę(Feb 6 2023, 14:30), 
blędu **nie** udało się zreprodukować.
W celach dalszej weryfikacji proszę o:
- zrzut ze stanu encji w HA,
- klucz serwisowy urządzenia dostępny w sekcji "_Details, updates and help_" aplikacji _**wBox**_,
- Zwrotkę z zapytania do urządzenia na endpoint http://<ip_address>/extended/state (zapytanie powinno być wykonane równolegle do sprawdzanego stanu encji HA)
 BR

**Comment by shibby20** [comment]
Na wersji 2022.12.4 wszystko działa poprawnie. Po aktualizacji do 2023.02.2 wygląda to następująco.
![HA](https://user-images.githubusercontent.com/9624725/217081015-3d4450c0-81b5-427a-a79c-bd13f66f7827.PNG)

thermobox włączony
![thermobox_on](https://user-images.githubusercontent.com/9624725/217081065-4cc0afdd-8f46-4abe-929e-dbb044fe801f.PNG)

thermobox wyłączony
![thermobox_off](https://user-images.githubusercontent.com/9624725/217081128-7396840d-7748-4c5d-ab86-291218c472cd.PNG)

Jak widać stan encji nadal jest heat mimo że w api state jest 0. Zmienił się jedynie atrybut hvac_action z idle na off.

Sama encja też wygląda błędnie
![thermostat_HA](https://user-images.githubusercontent.com/9624725/217081456-08f87c8c-3fc0-4994-a41d-cad3e427ecfb.PNG)

Na wersji ze stycznia jest dokładnie to samo a wystarczy że wgram wersję z grudnia tj 2022.12.4 i wszystko wraca do normy.
![thermobox_off_old](https://user-images.githubusercontent.com/9624725/217082661-1a17646d-cc0d-4d78-ba2c-a5dee195d26e.PNG)

![HA_old](https://user-images.githubusercontent.com/9624725/217082778-931abe2a-ec40-4efa-a57e-195607f3e76e.PNG)

Klucz serwisowy: 0--thermoBox--thB.1.0--0.1031--96b97e034ab5--false--11--0--0--5--0--0--5--421112

Pozdrawiam

**Comment by riokuu** [comment]
@shibby20 Witam, rozwiązanie problemu znajduje się na naszych serwerach. Bląd w kodzie znajduje się po stronie HA komponentu `blebox` . Proszę o [zgłoszenie Issue do Home Assistant Core](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml), liczę zachowanie takiego toku sprawy zaskutkuje szybszym wprowadzeniem poprawki do głównej gałęzi.
BR
