### ISSUE TITLE
No power consumption reads for switchBox v3

### ISSUE THREAD

**Issue by aslabicki** [blebox/blebox_uniapi#147]
* BleBox Python UniAPI version: 2.2.0
* Python version: 3.11.5
* Operating System: macOS

### Description

I don't see power consumption readings in the Home Assistant from my SwitchBox v3, which is returning all data under the API endpoint /api/relay/extended/state

Device details:
Device type: switchBox_v3
Hardware version: s_8.0
Firmware version: 0.1022
API type: switchBox
API level: 20200831

API Response:
```json
{
  "relays": [
    {
      "relay": 0,
      "state": 0,
      "stateAfterRestart": 2,
      "defaultForTime": 0,
      "name": "Output no 1"
    }
  ],
  "powerMeasuring": {
    "enabled": 1,
    "powerConsumption": [
      {
        "periodS": 3600,
        "value": 0,
        "state": 4
      }
    ]
  },
  "sensors": [
    {
      "type": "activePower",
      "value": 0,
      "trend": 0,
      "state": 4
    }
  ]
}
```

**Comment by shibby20** [comment]
read :)

https://github.com/blebox/blebox_uniapi/issues/137

https://github.com/home-assistant/core/pull/90516

https://github.com/home-assistant/core/issues/102148

**Comment by aslabicki** [comment]
Oh I saw it and I wonder it was included into 2023.10.3 but no... Good to know :)

**Comment by swistakm** [comment]
Should be fixed in v2.2.1 (see #152) and is waiting to be incorporated in home-assistant/core as a dependency update. Will keep you posted.

**Comment by aslabicki** [comment]
Fixed

**Comment by swistakm** [comment]
https://www.home-assistant.io/changelogs/core-2024.3
