### ISSUE TITLE
qustion

### ISSUE THREAD

**Issue by listek2336** [blebox/blebox_uniapi#22]
is this possible to add  to wlightbox dimming level like a wlightboxS

* BleBox Python UniAPI version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by gadgetmobile** [comment]
I tried once to support "brightness" by proportionally changing W channel and RGB (via HSL).

It worked by extracting "L" from HSL, and proportionally reducing it with W channel.

There are 3 main problems:
1 - color info loss (at very low levels, turning brightness up results in a different color)
2 - rounding (if you translate RGBW to HS+LW, and you translate back, you might not get the exact same colors)
3 - deciding on the proportion of brightness from the color (L) vs the (W) is arbitrary

If there's a proposed implementation for the above, I can probably add it (and enable to brightness), though it's probably a lot of work. (Especially edge cases for unit tests).

Instead, I'd just set the L (HSL from RGB channels) and W at the same time, but independently. (Based on your preferences).

**Comment by riokuu** [comment]
No updates on the thread.
